# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Sound Meter
email: psmokotnin@gmail.com
logo: /images/titledlogo.png
description: >- # this means to ignore newlines until "baseurl:"
  Open source dual-channel FFT optimization tool for sound systems tuning.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  psmokotnin

description: "Open Sound Meter is a cross-platform measurement application for tuning sound systems in real-time"


download_page: "https://github.com/psmokotnin/osm/releases"
payme_page: "https://www.paypal.me/psmokotnin/9.99"
issues_page: "https://github.com/psmokotnin/osm/issues"
source_page: "https://github.com/psmokotnin/osm"
license_page: "https://github.com/psmokotnin/osm/blob/master/LICENSE"
current_version: "v1.0.5"


# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
